In [1]:
import numpy as np
import pandas as pd
import string

### Generate data to be imported as .csv file

In [2]:
n_rows = 15
n_cols = 7
amplitude = 100    # Output range: 0–100
phase_shift = np.pi / 6
frequency = np.pi / 6

columns = ['A', 'B', 'C', 'D', 'E', 'F', 'G']
assert len(columns) == n_cols

# Create data
data = np.zeros((n_rows, n_cols))

# Nonlinear squashing factor: >1 squashes highs, boosts lows
power = 2.5

for i in range(n_rows):
    for j in range(n_cols):
        angle = i * frequency + j * phase_shift
        # Get normalized sine in [0, 1]
        normalized = (np.sin(angle) + 1) / 2
        # Skew toward 0: raise to power
        transformed = normalized**power
        data[i, j] = transformed * amplitude

# Create DataFrame with a–o as index
df = pd.DataFrame(data, columns=columns)
df.index = list(string.ascii_lowercase[:n_rows])
df = df.round(2)
df

        A       B       C       D       E       F       G
a   17.68   48.71   84.09  100.00   84.09   48.71   17.68
b   48.71   84.09  100.00   84.09   48.71   17.68    3.13
c   84.09  100.00   84.09   48.71   17.68    3.13    0.12
d  100.00   84.09   48.71   17.68    3.13    0.12    0.00
e   84.09   48.71   17.68    3.13    0.12    0.00    0.12
f   48.71   17.68    3.13    0.12    0.00    0.12    3.12
g   17.68    3.13    0.12    0.00    0.12    3.12   17.68
h    3.13    0.12    0.00    0.12    3.12   17.68   48.71
i    0.12    0.00    0.12    3.12   17.68   48.71   84.09
j    0.00    0.12    3.12   17.68   48.71   84.09  100.00
k    0.12    3.12   17.68   48.71   84.09  100.00   84.09
l    3.12   17.68   48.71   84.09  100.00   84.09   48.71
m   17.68   48.71   84.09  100.00   84.09   48.71   17.68
n   48.71   84.09  100.00   84.09   48.71   17.68    3.13
o   84.09  100.00   84.09   48.71   17.68    3.13    0.12

### Save directly as csv

In [3]:
# Reset index as first column
df = df.reset_index()
df = df.rename(columns={"index": "Categories"})
# Wrap row names with \text{} for correct read in
df["Categories"] = r"\text{" + df["Categories"] + r"}"
df

   Categories       A       B       C       D       E       F       G
0    \text{a}   17.68   48.71   84.09  100.00   84.09   48.71   17.68
1    \text{b}   48.71   84.09  100.00   84.09   48.71   17.68    3.13
2    \text{c}   84.09  100.00   84.09   48.71   17.68    3.13    0.12
3    \text{d}  100.00   84.09   48.71   17.68    3.13    0.12    0.00
4    \text{e}   84.09   48.71   17.68    3.13    0.12    0.00    0.12
5    \text{f}   48.71   17.68    3.13    0.12    0.00    0.12    3.12
6    \text{g}   17.68    3.13    0.12    0.00    0.12    3.12   17.68
7    \text{h}    3.13    0.12    0.00    0.12    3.12   17.68   48.71
8    \text{i}    0.12    0.00    0.12    3.12   17.68   48.71   84.09
9    \text{j}    0.00    0.12    3.12   17.68   48.71   84.09  100.00
10   \text{k}    0.12    3.12   17.68   48.71   84.09  100.00   84.09
11   \text{l}    3.12   17.68   48.71   84.09  100.00   84.09   48.71
12   \text{m}   17.68   48.71   84.09  100.00   84.09   48.71   17.68
13   \text{n}   48.71   84.09  100.00   84.09   48.71   17.68    3.13
14   \text{o}   84.09  100.00   84.09   48.71   17.68    3.13    0.12

In [4]:
csv_out_file = "table_plain.csv"

df.to_csv(csv_out_file, index=False, sep=",", encoding="utf-8")
print(f"Saved to {csv_out_file}")

Saved to table_plain.csv

### Wrap with `\gradient{}` for coloring the background

In [5]:
# Wrap float values with \text{\gradient{...}} for correct read in
df = df.map(lambda x: r"\text{\gradient{"+str(x)+"}}" if isinstance(x, float) else x)
df

,Categories,A,B,C,D,E,F,G
0,\text{a},\text{\gradient{17.68}},\text{\gradient{48.71}},\text{\gradient{84.09}},\text{\gradient{100.0}},\text{\gradient{84.09}},\text{\gradient{48.71}},\text{\gradient{17.68}}
1,\text{b},\text{\gradient{48.71}},\text{\gradient{84.09}},\text{\gradient{100.0}},\text{\gradient{84.09}},\text{\gradient{48.71}},\text{\gradient{17.68}},\text{\gradient{3.13}}
2,\text{c},\text{\gradient{84.09}},\text{\gradient{100.0}},\text{\gradient{84.09}},\text{\gradient{48.71}},\text{\gradient{17.68}},\text{\gradient{3.13}},\text{\gradient{0.12}}
3,\text{d},\text{\gradient{100.0}},\text{\gradient{84.09}},\text{\gradient{48.71}},\text{\gradient{17.68}},\text{\gradient{3.13}},\text{\gradient{0.12}},\text{\gradient{0.0}}
4,\text{e},\text{\gradient{84.09}},\text{\gradient{48.71}},\text{\gradient{17.68}},\text{\gradient{3.13}},\text{\gradient{0.12}},\text{\gradient{0.0}},\text{\gradient{0.12}}
5,\text{f},\text{\gradient{48.71}},\text{\gradient{17.68}},\text{\gradient{3.13}},\text{\gradient{0.12}},\text{\gradient{0.0}},\text{\gradient{0.12}},\text{\gradient{3.12}}
6,\text{g},\text{\gradient{17.68}},\text{\gradient{3.13}},\text{\gradient{0.12}},\text{\gradient{0.0}},\text{\gradient{0.12}},\text{\gradient{3.12}},\text{\gradient{17.68}}
7,\text{h},\text{\gradient{3.13}},\text{\gradient{0.12}},\text{\gradient{0.0}},\text{\gradient{0.12}},\text{\gradient{3.12}},\text{\gradient{17.68}},\text{\gradient{48.71}}
8,\text{i},\text{\gradient{0.12}},\text{\gradient{0.0}},\text{\gradient{0.12}},\text{\gradient{3.12}},\text{\gradient{17.68}},\text{\gradient{48.71}},\text{\gradient{84.09}}
9,\text{j},\text{\gradient{0.0}},\text{\gradient{0.12}},\text{\gradient{3.12}},\text{\gradient{17.68}},\text{\gradient{48.71}},\text{\gradient{84.09}},\text{\gradient{100.0}}
10,\text{k},\text{\gradient{0.12}},\text{\gradient{3.12}},\text{\gradient{17.68}},\text{\gradient{48.71}},\text{\gradient{84.09}},\text{\gradient{100.0}},\text{\gradient{84.09}}
11,\text{l},\text{\gradient{3.12}},\text{\gradient{17.68}},\text{\gradient{48.71}},\text{\gradient{84.09}},\text{\gradient{100.0}},\text{\gradient{84.09}},\text{\gradient{48.71}}
12,\text{m},\text{\gradient{17.68}},\text{\gradient{48.71}},\text{\gradient{84.09}},\text{\gradient{100.0}},\text{\gradient{84.09}},\text{\gradient{48.71}},\text{\gradient{17.68}}
13,\text{n},\text{\gradient{48.71}},\text{\gradient{84.09}},\text{\gradient{100.0}},\text{\gradient{84.09}},\text{\gradient{48.71}},\text{\gradient{17.68}},\text{\gradient{3.13}}
14,\text{o},\text{\gradient{84.09}},\text{\gradient{100.0}},\text{\gradient{84.09}},\text{\gradient{48.71}},\text{\gradient{17.68}},\text{\gradient{3.13}},\text{\gradient{0.12}}

In [6]:
csv_out_file = "table_gradient.csv"

df.to_csv(csv_out_file, index=False, sep=",", encoding="utf-8")
print(f"Saved to {csv_out_file}")

Saved to table_gradient.csv